"""
Assemble exactly the artefacts the Phase-1 submission form asks for.

    python src/make_submission.py

Why this exists: the intake form accepts ONE file per slot. Hand-copying files
into a folder is how stale or mismatched uploads happen, so the upload set is
*generated* from the canonical outputs on every ./run_all.sh and verified by
checksum against its source. The manifest records SHA-256 of both the source
and the copy, so "did you upload the same file the repo ships?" is answerable.

Outputs (in submission/, which is git-ignored because it is derived):
  Social_Engine_Posts_Clean.csv        slot "Cleaned Dataset" - the one to upload
  Social_Engine_Cleaned_AllTables.json  alternative single-file dataset
  Phase1_EDA_Report.pdf                 slot "EDA Report"
  MANIFEST.md                           sizes, checksums, which file goes where
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CLEAN, OUT, SUB = ROOT / "data" / "clean", ROOT / "output", ROOT / "submission"
sys.path.insert(0, str(ROOT / "src"))
from config import TEAM_MEMBERS, TEAM_NAME  # noqa: E402

LIMIT = 10 * 1024 * 1024  # the form's per-file cap


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def records(df: pd.DataFrame) -> list[dict]:
    """Plain-Python records; NaN -> null so the JSON is strictly valid."""
    return json.loads(df.to_json(orient="records"))


def main() -> int:
    SUB.mkdir(exist_ok=True)
    rows = []

    # ---- slot 1: cleaned dataset, as the canonical CSV -------------------
    src_csv = CLEAN / "Social_Engine_Posts_Clean.csv"
    dst = SUB / src_csv.name
    shutil.copyfile(src_csv, dst)
    rows.append(("Cleaned Dataset", dst, src_csv))

    # ---- slot 1 (alternative): every table in one self-describing JSON ---
    posts = pd.read_csv(src_csv)
    users = pd.read_csv(CLEAN / "Social_Engine_Users_Clean.csv")
    held = pd.read_csv(CLEAN / "Social_Engine_Posts_EmptyText_HeldOut.csv")
    log = pd.read_csv(CLEAN / "repair_log.csv")
    summary = json.loads((CLEAN / "cleaning_summary.json").read_text())

    bundle = {
        "dataset": "Social Engine - Dataset 01, recovered from the corrupted intake",
        "competition": "Data Vortex - Round 1, Phase 1 (Rebuilding the Social Engine)",
        "team": TEAM_NAME,
        "members": TEAM_MEMBERS,
        "generated_by": "src/make_submission.py (from src/clean_data.py output)",
        "row_counts": {
            "posts": len(posts),
            "posts_empty_text_held_out": len(held),
            "users": len(users),
            "repair_log_actions": len(log),
        },
        "reading_guide": {
            "posts": "the analysis set; exactly what the EDA report and the SQL "
                     "database were built from",
            "flag_* columns": "one column per repair, so every change is reversible "
                              "by filtering instead of by trusting prose",
            "likes = null": "missing in the source and deliberately NOT imputed "
                            "(fabrication is prohibited by the rules)",
            "posts_empty_text_held_out": "1,779 rows whose text is unrecoverable; "
                                         "kept, not deleted, and excluded from "
                                         "text-derived features",
        },
        "cleaning_summary": summary,
        "repair_log": records(log),
        "posts": records(posts),
        "posts_empty_text_held_out": records(held),
        "users": records(users),
    }
    js = SUB / "Social_Engine_Cleaned_AllTables.json"
    js.write_text(json.dumps(bundle, separators=(",", ":")))
    assert len(json.loads(js.read_text())["posts"]) == len(posts)

    # ---- slot 2: EDA report ----------------------------------------------
    src_pdf = OUT / "Phase1_EDA_Report.pdf"
    dst = SUB / src_pdf.name
    shutil.copyfile(src_pdf, dst)
    rows.append(("EDA Report (.pdf)", dst, src_pdf))

    # ---- manifest ---------------------------------------------------------
    lines = [
        "# Phase-1 upload set",
        "",
        "Generated by `python src/make_submission.py` (step 9 of `./run_all.sh`).",
        "Every copy is byte-identical to the file in the repo, so the upload and",
        "the public repository cannot disagree.",
        "",
        "| Form slot | Upload this | Size | vs 10 MB cap | SHA-256 (== repo source) |",
        "|---|---|---:|---|---|",
    ]
    ok = True
    for slot, dst, src in rows:
        size = dst.stat().st_size
        fits = size <= LIMIT
        ok &= fits
        same = sha(dst) == sha(src)
        ok &= same
        lines.append(
            f"| {slot} | `{dst.name}` | {size / 1048576:.2f} MB | "
            f"{'fits' if fits else 'OVER LIMIT'} | `{sha(dst)[:16]}…` "
            f"{'==' if same else '!='} `{src.relative_to(ROOT)}` |"
        )
    alt = js.stat().st_size
    lines += [
        "",
        f"Alternative for the dataset slot: `Social_Engine_Cleaned_AllTables.json` "
        f"({alt / 1048576:.2f} MB, {'fits' if alt <= LIMIT else 'OVER'}) - posts + "
        "users + hold-out + repair log + the full cleaning summary in one file, for "
        "reviewers who want everything without opening the repo.",
        "",
        "Third slot: the repository URL (must be public).",
    ]
    (SUB / "MANIFEST.md").write_text("\n".join(lines) + "\n")

    for slot, dst, src in rows:
        print(f"[submit] {slot:22} {dst.name:42} {dst.stat().st_size/1048576:6.2f} MB")
    print(f"[submit] {'(alt. one file)':22} {js.name:42} {alt/1048576:6.2f} MB")
    if not ok:
        print("[submit] PROBLEM - a file exceeds the cap or differs from its source")
        return 1
    print("[submit] all files under the 10 MB cap and byte-identical to the repo copies")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
